name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this matches the Pages source

permissions:
  contents: read
  pages: write
  id-token: write  # Required for GitHub OIDC authentication

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll & Dependencies
        run: |
          if [ ! -f "Gemfile" ]; then
            echo 'source "https://rubygems.org"' > Gemfile
            echo 'gem "jekyll"' >> Gemfile
            echo 'gem "github-pages"' >> Gemfile
          fi
          bundle install

      - name: Build Jekyll Site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Inject Mermaid.js for Rendering
        run: |
          echo "<script type='module'>
            import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
            mermaid.initialize({ startOnLoad: true });

            document.addEventListener('DOMContentLoaded', function() {
                document.querySelectorAll('pre code.language-mermaid').forEach((block) => {
                    const mermaidDiv = document.createElement('div');
                    mermaidDiv.classList.add('mermaid');
                    mermaidDiv.textContent = block.textContent;
                    block.parentElement.replaceWith(mermaidDiv);
                });
                mermaid.init();
            });
          </script>" >> _site/index.html

      - name: Ensure GitHub Pages Artifact Upload Completes
        run: sleep 10  # Prevents race conditions before upload

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Wait for Artifact Availability
        run: sleep 15  # Ensures artifact is fully available

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
