name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Ensure Ruby version is compatible

      - name: Install Jekyll
        run: |
          gem install jekyll
          [ -f Gemfile ] && bundle install || echo "No Gemfile found, skipping bundle install"

      - name: Build Jekyll Site
        run: JEKYLL_ENV=production jekyll build

      - name: Inject Mermaid.js for Rendering
        run: |
          echo "<script type='module'>
            import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
            mermaid.initialize({ startOnLoad: true });

            document.addEventListener('DOMContentLoaded', function() {
                document.querySelectorAll('pre code.language-mermaid').forEach((block) => {
                    const mermaidDiv = document.createElement('div');
                    mermaidDiv.classList.add('mermaid');
                    mermaidDiv.textContent = block.textContent;
                    block.parentElement.replaceWith(mermaidDiv);
                });
                mermaid.init();
            });
          </script>" >> _site/index.html

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2  # Fixed version

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
