name: Publish README to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html with Mermaid support
        run: |
          pandoc README.md -o index.html \
          --metadata title="Project Documentation" \
          --standalone \
          -V header-includes='<script src="https://cdn.jsdelivr.net/npm/mermaid@9.4.3/dist/mermaid.min.js"></script><style>.mermaid-container { overflow: auto; width: 100%; height: 90vh; border: 1px solid #ddd; background: white; } body { font-family: Arial, sans-serif; text-align: center; background-color: #f8f9fa; } h1, h2 { font-size: 24px; }</style>'
          # Debug: Show the initial Mermaid code block
          echo "HTML before sed commands - Mermaid section:"
          grep -A 10 "<pre><code class=\"language-mermaid\"" index.html || echo "No mermaid code block found"
          # Debug: Show the <head> section to verify script inclusion
          echo "HTML <head> section before modifications:"
          grep -A 5 "<head>" index.html

      - name: Fix Mermaid class in index.html
        run: |
          # Debug: Show the exact line we're trying to replace
          echo "Before sed - Full Mermaid code block:"
          grep -A 50 "<pre><code class=\"language-mermaid\"" index.html || echo "No mermaid code block found"
          # Replace <pre><code class="language-mermaid"> with <div class="mermaid-container"><div class="mermaid">
          sed -i 's/<pre><code class="language-mermaid"[^>]*>/<div class="mermaid-container"><div class="mermaid">/g' index.html
          # Replace </code></pre> with </div></div>
          sed -i 's/<\/code><\/pre>/<\/div><\/div>/g' index.html
          # Debug: Show the modified Mermaid code block
          echo "After sed - Modified Mermaid code block:"
          grep -A 50 "<div class=\"mermaid-container\"" index.html || echo "No mermaid container found after sed"
          # Append the updated Mermaid initialization script with enhanced logging
          echo '<script>document.addEventListener("DOMContentLoaded", function() { console.log("Mermaid script loaded. Initializing..."); try { mermaid.initialize({ startOnLoad: false }); console.log("Mermaid initialized. Starting render..."); setTimeout(() => { const mermaidElements = document.querySelectorAll(".mermaid"); console.log("Found", mermaidElements.length, "Mermaid elements"); mermaid.run().then(() => console.log("Mermaid rendering completed successfully")).catch(error => console.error("Mermaid rendering failed:", error)); }, 100); } catch (e) { console.error("Mermaid initialization failed:", e); } });</script>' >> index.html
          # Debug: Show the final <head> and <body> sections
          echo "Final HTML <head> section:"
          grep -A 5 "<head>" index.html
          echo "Final HTML <body> section (Mermaid and script):"
          grep -A 50 "<div class=\"mermaid-container\"" index.html || echo "No mermaid container found in final HTML"
          grep -A 5 "<script>document.addEventListener" index.html || echo "No initialization script found"

      - name: Setup gh-pages branch
        run: |
          echo "Current branch before setup: $(git branch --show-current)"
          mv index.html /tmp/index.html
          git fetch origin gh-pages && git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf .)
          mv /tmp/index.html .
          echo "Current branch after setup: $(git branch --show-current)"

      - name: Commit and Push Changes
        run: |
          echo "Current branch before commit: $(git branch --show-current)"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html with latest README" || echo "No changes to commit"
          git push origin gh-pages

      - name: Output GitHub Pages URL
        run: |
          echo "The deployed site should be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
