name: Publish README to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html with Mermaid support
        run: |
          pandoc README.md -o index.html \
          --metadata title="Project Documentation" \
          --standalone \
          -V header-includes='<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>'

      - name: Fix Mermaid class in index.html
        run: |
          sed -i 's/<pre><code class="language-mermaid">/<pre class="mermaid">/g' index.html
          sed -i 's/<\/code><\/pre>/<\/pre>/g' index.html
          echo '<script>document.addEventListener("DOMContentLoaded", function() { mermaid.initialize({startOnLoad: true}); });</script>' >> index.html
          cat index.html

      - name: Setup gh-pages branch
        run: |
          echo "Current branch before setup: $(git branch --show-current)"
          mv index.html /tmp/index.html
          git fetch origin gh-pages && git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf .)
          mv /tmp/index.html .
          echo "Current branch after setup: $(git branch --show-current)"

      - name: Commit and Push Changes
        run: |
          echo "Current branch before commit: $(git branch --show-current)"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html with latest README" || echo "No changes to commit"
          git push origin gh-pages

      - name: Output GitHub Pages URL
        run: |
          echo "The deployed site should be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
