name: Publish README to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate HTML from README
        run: |
          pandoc README.md -o index.html \
            --metadata title="Project Documentation" \
            --standalone \
            --highlight-style=pygments \
            -V header-includes='<script type="module">import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs"; mermaid.initialize({ startOnLoad: true });</script><style>.mermaid-container { overflow: auto; width: 100%; height: 90vh; border: 1px solid #ddd; background: white; } body { font-family: Arial, sans-serif; text-align: center; background-color: #f8f9fa; } h1, h2 { font-size: 24px; }</style>'

      - name: Fix Mermaid Blocks
        run: |
          sed -i 's|<pre><code class="language-mermaid">|<div class="mermaid">|g' index.html
          sed -i 's|</code></pre>|</div>|g' index.html
          echo '<script>document.addEventListener("DOMContentLoaded", function() {if (window.mermaid) {mermaid.init(undefined, document.querySelectorAll(".mermaid"));}});</script>' >> index.html

      - name: Switch to GitHub Pages Branch
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          mv ../index.html .
          touch .nojekyll

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy updated README to GitHub Pages" || true
          git push origin gh-pages

      - name: Output Deployment URL
        run: echo "Site available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
