name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you are using

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: |
          mkdir -p docs
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Decker Family Survey</title>
              <script type="module">
                  import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs";
                  mermaid.initialize({ startOnLoad: true });
              </script>
              <style>
                  body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; }
                  h1, h2, h3 { color: #333; }
                  pre { background: #f4f4f4; padding: 10px; border-radius: 5px; }
                  .mermaid { text-align: center; margin-top: 20px; }
              </style>
          </head>
          <body>
              <article>' > docs/index.html
          pandoc README.md -f markdown -t html >> docs/index.html
          echo '</article></body></html>' >> docs/index.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
