name: Publish README to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html with Mermaid support
        run: |
          pandoc README.md -o index.html \
          --metadata title="Project Documentation" \
          --standalone \
          -V header-includes='<script src="https://cdn.jsdelivr.net/npm/mermaid@11.0.0/dist/mermaid.min.js"></script>'
          # Debug: Show HTML before modification
          echo "HTML before sed commands:"
          grep "mermaid" index.html || echo "No mermaid code block found"

      - name: Fix Mermaid class in index.html
        run: |
          # Debug: Show the exact line we're trying to replace
          echo "Before sed - looking for mermaid code block:"
          grep "<pre><code class=\"language-mermaid\"" index.html
          # Replace <pre><code class="language-mermaid"> with <pre class="mermaid">
          sed -i 's/<pre><code class="language-mermaid"[^>]*>/<pre class="mermaid">/g' index.html
          # Replace </code></pre> with </pre>
          sed -i 's/<\/code><\/pre>/<\/pre>/g' index.html
          # Debug: Show the modified line
          echo "After sed - modified mermaid code block:"
          grep "<pre class=\"mermaid\"" index.html || echo "No mermaid class found after sed"
          # Append the updated Mermaid initialization script with debug logging
          echo '<script>document.addEventListener("DOMContentLoaded", function() { console.log("Mermaid initializing..."); mermaid.initialize({ startOnLoad: true }); mermaid.run().then(() => console.log("Mermaid rendering complete")); });</script>' >> index.html
          # Debug: Show the final HTML
          echo "Final HTML:"
          cat index.html

      - name: Setup gh-pages branch
        run: |
          echo "Current branch before setup: $(git branch --show-current)"
          mv index.html /tmp/index.html
          git fetch origin gh-pages && git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf .)
          mv /tmp/index.html .
          echo "Current branch after setup: $(git branch --show-current)"

      - name: Commit and Push Changes
        run: |
          echo "Current branch before commit: $(git branch --show-current)"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html with latest README" || echo "No changes to commit"
          git push origin gh-pages

      - name: Output GitHub Pages URL
        run: |
          echo "The deployed site should be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
