name: Publish README to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html with Mermaid support
        run: |
          pandoc README.md -o index.html \
          --metadata title="Project Documentation" \
          --standalone \
          -V header-includes='<script type="module">import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs"; mermaid.initialize({ startOnLoad: true });</script><style>.mermaid-container { overflow: auto; width: 100%; height: 90vh; border: 1px solid #ddd; background: white; } body { font-family: Arial, sans-serif; text-align: center; background-color: #f8f9fa; } h1, h2 { font-size: 24px; }</style>'

      - name: Ensure Mermaid Blocks Render Properly in index.html
        run: |
          # Debug: Show any Mermaid code blocks before modification
          echo "Before sed - Mermaid-related code blocks:"
          grep -A 50 "<pre>" index.html | grep -B 5 -A 50 "mermaid\|flowchart" || echo "No mermaid-related code blocks found"

          # Replace incorrectly formatted Mermaid code blocks with proper <div> containers
          sed -i 's/<pre><code class="language-mermaid">/<div class="mermaid">/g' index.html
          sed -i 's/<pre><code class="mermaid">/<div class="mermaid">/g' index.html
          sed -i 's/<\/code><\/pre>/<\/div>/g' index.html

          # Debug: Show updated Mermaid sections after modifications
          echo "After sed - Modified Mermaid code blocks:"
          grep -B 5 -A 50 "<div class=\"mermaid\"" index.html || echo "No mermaid container found after sed"

          # Add Mermaid reinitialization script at the bottom of the HTML file
          echo '<script>document.addEventListener("DOMContentLoaded", function() { setTimeout(() => { if (window.mermaid) { console.log("Initializing Mermaid..."); mermaid.init(undefined, document.querySelectorAll(".mermaid")); } else { console.error("Mermaid script not loaded!"); } }, 1000); });</script>' >> index.html

      - name: Prepare GitHub Pages Deployment
        run: |
          echo "Current branch before setup: $(git branch --show-current)"

          mv index.html /tmp/index.html

          # Ensure we switch to gh-pages correctly
          git fetch origin gh-pages && git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf .)

          mv /tmp/index.html .

          # Ensure .nojekyll exists, but do NOT move it if it already exists
          touch .nojekyll

          echo "Current branch after setup: $(git branch --show-current)"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html .nojekyll
          git commit -m "Update index.html with latest README and fix Mermaid rendering" || echo "No changes to commit"
          git push origin gh-pages

      - name: Output GitHub Pages URL
        run: |
          echo "The deployed site should be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
